app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
# app/config/routing.yml
user_registration:
    path:     /register
    defaults: { _controller: AppBundle:Registration:register }

logout:
    path: /logout
    
login:
    path: /login
    
home:
    path: /
    
mydashboard:
    path: /mydashboard
    defaults: { _controller: AppBundle:Mydashboard:mydashboard }

addrequest:
    path: /addrequest
    defaults: { _controller: AppBundle:AddRequest:addRequest }
    
takeInSearch_ajax_update:
    pattern:  /update/data/from/ajax/call
    defaults: { _controller: AppBundle:Search:takeRequest }    
    
# hwi_oauth_redirect:
#     resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
#     prefix:   /connect

# hwi_oauth_login:
#     resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
#     prefix:   /login