app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
# app/config/routing.yml
user_registration:
    path:     /register
    defaults: { _controller: AppBundle:Registration:register }

add_request:
    path:     /home
    defaults: { _controller: AppBundle:Home:add }

# hwi_oauth_redirect:
#     resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
#     prefix:   /connect

# hwi_oauth_login:
#     resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
#     prefix:   /login