<?php

namespace AppBundle\Entity;

/**
 * DeliveryRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeliveryRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
