<?php

namespace AppBundle\Entity;

/**
 * TakeRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TakeRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
